### ISSUE TITLE
Http\Adapter\Guzzle6\Client not an instance of Ivory\HttpAdapter\HttpAdapterInterface

### ISSUE THREAD

**Issue by xarasbir** [geocoder-php/Geocoder#525] opened 2016-09-01 00:46 UTC
This is what I have : 
```
$adapter  = new \Http\Adapter\Guzzle6\Client();
$geocoder = new \Geocoder\Provider\GoogleMaps($adapter, null, null, true, env('GOOGLEMAP_API_KEY')); 
return $geocoder->reverse($this->lat, $this->lng);
```

and i'm getting the following error : 

> TypeError: Argument 1 passed to Geocoder\Provider\GoogleMaps::__construct() must be an instance of Ivory\HttpAdapter\HttpAdapterInterface, instance of Http\Adapter\Guzzle6\Client given

**Comment by Nyholm** [comment] 2016-09-01 09:13
This is a duplicate of #524

**Closed by Nyholm** 2016-09-01 09:13 UTC
