### ISSUE TITLE
"egeloen/http-adapter" deprecated

### ISSUE THREAD

**Issue by dereuromark** [geocoder-php/Geocoder#484] opened 2016-01-16 00:54 UTC
Composer message:

> Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.

You should remove "egeloen/http-adapter" from require, and instead move it to `require-dev`.
This suffices for testing but allows people to use other not deprecated packages instead.
In general it is always a good idea to not directly include those proposed dependencies in require, but keep them in require-dev or suggest.

**Comment by drupol** [comment] 2016-01-18 14:38
I'm working on a GuzzleHttpAdapter in the Drupal module so I can use Guzzle directly.

**Comment by willdurand** [comment] 2016-01-19 07:22
Yep. Duplicate of #480. Should be fixed by #487

**Closed by willdurand** 2016-01-19 07:22 UTC
